# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
