# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_pullrequest_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='is_merged',
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('merged', 'merged')], default='pending', max_length=20),
        ),
    ]
